[package]
name = "rust-pw-manager"
version = "0.1.0"
authors = ["noesterle <noesterle1@gmail.com>"]

[dependencies]
rusqlite = "0.12.0"
ring = "0.12.1"
rpassword = "2.0.0"

[lib]
name="mylib"
path="src/lib.rs"
